name: Checkmarx One Scan

on:
  workflow_dispatch:

jobs:
  cxone:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkmarx AST Github Action
        uses: Checkmarx/ast-github-action@2.0.23
        with:
          base_uri: https://eu-2.ast.checkmarx.net
          cx_tenant: itracing-nfr
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          branch: main
          additional_params: --threshold "sast-high=10; sast-medium=20; sca-high=10" --report-format sarif --output-path .

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with: 
          sarif_file: cx_result.sarif
