on:
  pull_request:
    branches:
    - main

jobs:
  release-image:
    environment: 'Apalia - Lab'
    name: build docker image
    runs-on: docker:26-cli

    steps:
    - name: build image
      run: |
        echo "Building image..."
        docker build -t craftedby-backend
        docker image tag craftedby-backend ${{ vars.DOCKER_HUB_REPO }}/craftedby-backend:v1.0.0

    - name: release image
      run: |
        echo "Logging to docker hub and pushing image to ${{ vars.DOCKER_HUB_REPO }}/craftedby-backend"
        docker login -u ${{ vars.DOCKER_HUB_USERNAME }} -p ${{ vars.DOCKER_HUB_PASSWORD }}
        docker push ${{ vars.DOCKER_HUB_REPO }}/craftedby-backend:v1.0.0
